/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for AddCommentRequest type.
 */
public class AddCommentRequest {
    private String comment;
    private int userId;
    private Content content;

    /**
     * Default constructor.
     */
    public AddCommentRequest() {
    }

    /**
     * Initialization constructor.
     * @param  comment  String value for comment.
     * @param  userId  int value for userId.
     * @param  content  Content value for content.
     */
    public AddCommentRequest(
            String comment,
            int userId,
            Content content) {
        this.comment = comment;
        this.userId = userId;
        this.content = content;
    }

    /**
     * Getter for Comment.
     * @return Returns the String
     */
    @JsonGetter("comment")
    public String getComment() {
        return comment;
    }

    /**
     * Setter for Comment.
     * @param comment Value for String
     */
    @JsonSetter("comment")
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for UserId.
     * @return Returns the int
     */
    @JsonGetter("userId")
    public int getUserId() {
        return userId;
    }

    /**
     * Setter for UserId.
     * @param userId Value for int
     */
    @JsonSetter("userId")
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * Getter for Content.
     * @return Returns the Content
     */
    @JsonGetter("content")
    public Content getContent() {
        return content;
    }

    /**
     * Setter for Content.
     * @param content Value for Content
     */
    @JsonSetter("content")
    public void setContent(Content content) {
        this.content = content;
    }

    /**
     * Converts this AddCommentRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AddCommentRequest [" + "comment=" + comment + ", userId=" + userId + ", content="
                + content + "]";
    }

    /**
     * Builds a new {@link AddCommentRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AddCommentRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(comment, userId, content);
        return builder;
    }

    /**
     * Class to build instances of {@link AddCommentRequest}.
     */
    public static class Builder {
        private String comment;
        private int userId;
        private Content content;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  comment  String value for comment.
         * @param  userId  int value for userId.
         * @param  content  Content value for content.
         */
        public Builder(String comment, int userId, Content content) {
            this.comment = comment;
            this.userId = userId;
            this.content = content;
        }

        /**
         * Setter for comment.
         * @param  comment  String value for comment.
         * @return Builder
         */
        public Builder comment(String comment) {
            this.comment = comment;
            return this;
        }

        /**
         * Setter for userId.
         * @param  userId  int value for userId.
         * @return Builder
         */
        public Builder userId(int userId) {
            this.userId = userId;
            return this;
        }

        /**
         * Setter for content.
         * @param  content  Content value for content.
         * @return Builder
         */
        public Builder content(Content content) {
            this.content = content;
            return this;
        }

        /**
         * Builds a new {@link AddCommentRequest} object using the set fields.
         * @return {@link AddCommentRequest}
         */
        public AddCommentRequest build() {
            return new AddCommentRequest(comment, userId, content);
        }
    }
}
