/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for AddMovieRequest type.
 */
public class AddMovieRequest {
    private int durationInMinutes;
    private String genre;
    private String director;
    private String releaseDate;
    private String title;

    /**
     * Default constructor.
     */
    public AddMovieRequest() {
    }

    /**
     * Initialization constructor.
     * @param  durationInMinutes  int value for durationInMinutes.
     * @param  genre  String value for genre.
     * @param  director  String value for director.
     * @param  releaseDate  String value for releaseDate.
     * @param  title  String value for title.
     */
    public AddMovieRequest(
            int durationInMinutes,
            String genre,
            String director,
            String releaseDate,
            String title) {
        this.durationInMinutes = durationInMinutes;
        this.genre = genre;
        this.director = director;
        this.releaseDate = releaseDate;
        this.title = title;
    }

    /**
     * Getter for DurationInMinutes.
     * @return Returns the int
     */
    @JsonGetter("durationInMinutes")
    public int getDurationInMinutes() {
        return durationInMinutes;
    }

    /**
     * Setter for DurationInMinutes.
     * @param durationInMinutes Value for int
     */
    @JsonSetter("durationInMinutes")
    public void setDurationInMinutes(int durationInMinutes) {
        this.durationInMinutes = durationInMinutes;
    }

    /**
     * Getter for Genre.
     * @return Returns the String
     */
    @JsonGetter("genre")
    public String getGenre() {
        return genre;
    }

    /**
     * Setter for Genre.
     * @param genre Value for String
     */
    @JsonSetter("genre")
    public void setGenre(String genre) {
        this.genre = genre;
    }

    /**
     * Getter for Director.
     * @return Returns the String
     */
    @JsonGetter("director")
    public String getDirector() {
        return director;
    }

    /**
     * Setter for Director.
     * @param director Value for String
     */
    @JsonSetter("director")
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * Getter for ReleaseDate.
     * @return Returns the String
     */
    @JsonGetter("releaseDate")
    public String getReleaseDate() {
        return releaseDate;
    }

    /**
     * Setter for ReleaseDate.
     * @param releaseDate Value for String
     */
    @JsonSetter("releaseDate")
    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Converts this AddMovieRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AddMovieRequest [" + "durationInMinutes=" + durationInMinutes + ", genre=" + genre
                + ", director=" + director + ", releaseDate=" + releaseDate + ", title=" + title
                + "]";
    }

    /**
     * Builds a new {@link AddMovieRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AddMovieRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(durationInMinutes, genre, director, releaseDate, title);
        return builder;
    }

    /**
     * Class to build instances of {@link AddMovieRequest}.
     */
    public static class Builder {
        private int durationInMinutes;
        private String genre;
        private String director;
        private String releaseDate;
        private String title;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  durationInMinutes  int value for durationInMinutes.
         * @param  genre  String value for genre.
         * @param  director  String value for director.
         * @param  releaseDate  String value for releaseDate.
         * @param  title  String value for title.
         */
        public Builder(int durationInMinutes, String genre, String director, String releaseDate,
                String title) {
            this.durationInMinutes = durationInMinutes;
            this.genre = genre;
            this.director = director;
            this.releaseDate = releaseDate;
            this.title = title;
        }

        /**
         * Setter for durationInMinutes.
         * @param  durationInMinutes  int value for durationInMinutes.
         * @return Builder
         */
        public Builder durationInMinutes(int durationInMinutes) {
            this.durationInMinutes = durationInMinutes;
            return this;
        }

        /**
         * Setter for genre.
         * @param  genre  String value for genre.
         * @return Builder
         */
        public Builder genre(String genre) {
            this.genre = genre;
            return this;
        }

        /**
         * Setter for director.
         * @param  director  String value for director.
         * @return Builder
         */
        public Builder director(String director) {
            this.director = director;
            return this;
        }

        /**
         * Setter for releaseDate.
         * @param  releaseDate  String value for releaseDate.
         * @return Builder
         */
        public Builder releaseDate(String releaseDate) {
            this.releaseDate = releaseDate;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Builds a new {@link AddMovieRequest} object using the set fields.
         * @return {@link AddMovieRequest}
         */
        public AddMovieRequest build() {
            return new AddMovieRequest(durationInMinutes, genre, director, releaseDate, title);
        }
    }
}
