/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for AddSeriesRequest type.
 */
public class AddSeriesRequest {
    private String title;
    private int numberOfSeasons;
    private int numberOfEpisodes;
    private int durationInMinutes;
    private String genre;
    private String director;
    private String releaseDate;

    /**
     * Default constructor.
     */
    public AddSeriesRequest() {
    }

    /**
     * Initialization constructor.
     * @param  title  String value for title.
     * @param  numberOfSeasons  int value for numberOfSeasons.
     * @param  numberOfEpisodes  int value for numberOfEpisodes.
     * @param  durationInMinutes  int value for durationInMinutes.
     * @param  genre  String value for genre.
     * @param  director  String value for director.
     * @param  releaseDate  String value for releaseDate.
     */
    public AddSeriesRequest(
            String title,
            int numberOfSeasons,
            int numberOfEpisodes,
            int durationInMinutes,
            String genre,
            String director,
            String releaseDate) {
        this.title = title;
        this.numberOfSeasons = numberOfSeasons;
        this.numberOfEpisodes = numberOfEpisodes;
        this.durationInMinutes = durationInMinutes;
        this.genre = genre;
        this.director = director;
        this.releaseDate = releaseDate;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for NumberOfSeasons.
     * @return Returns the int
     */
    @JsonGetter("numberOfSeasons")
    public int getNumberOfSeasons() {
        return numberOfSeasons;
    }

    /**
     * Setter for NumberOfSeasons.
     * @param numberOfSeasons Value for int
     */
    @JsonSetter("numberOfSeasons")
    public void setNumberOfSeasons(int numberOfSeasons) {
        this.numberOfSeasons = numberOfSeasons;
    }

    /**
     * Getter for NumberOfEpisodes.
     * @return Returns the int
     */
    @JsonGetter("numberOfEpisodes")
    public int getNumberOfEpisodes() {
        return numberOfEpisodes;
    }

    /**
     * Setter for NumberOfEpisodes.
     * @param numberOfEpisodes Value for int
     */
    @JsonSetter("numberOfEpisodes")
    public void setNumberOfEpisodes(int numberOfEpisodes) {
        this.numberOfEpisodes = numberOfEpisodes;
    }

    /**
     * Getter for DurationInMinutes.
     * @return Returns the int
     */
    @JsonGetter("durationInMinutes")
    public int getDurationInMinutes() {
        return durationInMinutes;
    }

    /**
     * Setter for DurationInMinutes.
     * @param durationInMinutes Value for int
     */
    @JsonSetter("durationInMinutes")
    public void setDurationInMinutes(int durationInMinutes) {
        this.durationInMinutes = durationInMinutes;
    }

    /**
     * Getter for Genre.
     * @return Returns the String
     */
    @JsonGetter("genre")
    public String getGenre() {
        return genre;
    }

    /**
     * Setter for Genre.
     * @param genre Value for String
     */
    @JsonSetter("genre")
    public void setGenre(String genre) {
        this.genre = genre;
    }

    /**
     * Getter for Director.
     * @return Returns the String
     */
    @JsonGetter("director")
    public String getDirector() {
        return director;
    }

    /**
     * Setter for Director.
     * @param director Value for String
     */
    @JsonSetter("director")
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * Getter for ReleaseDate.
     * @return Returns the String
     */
    @JsonGetter("releaseDate")
    public String getReleaseDate() {
        return releaseDate;
    }

    /**
     * Setter for ReleaseDate.
     * @param releaseDate Value for String
     */
    @JsonSetter("releaseDate")
    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * Converts this AddSeriesRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AddSeriesRequest [" + "title=" + title + ", numberOfSeasons=" + numberOfSeasons
                + ", numberOfEpisodes=" + numberOfEpisodes + ", durationInMinutes="
                + durationInMinutes + ", genre=" + genre + ", director=" + director
                + ", releaseDate=" + releaseDate + "]";
    }

    /**
     * Builds a new {@link AddSeriesRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AddSeriesRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(title, numberOfSeasons, numberOfEpisodes, durationInMinutes,
                genre, director, releaseDate);
        return builder;
    }

    /**
     * Class to build instances of {@link AddSeriesRequest}.
     */
    public static class Builder {
        private String title;
        private int numberOfSeasons;
        private int numberOfEpisodes;
        private int durationInMinutes;
        private String genre;
        private String director;
        private String releaseDate;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  title  String value for title.
         * @param  numberOfSeasons  int value for numberOfSeasons.
         * @param  numberOfEpisodes  int value for numberOfEpisodes.
         * @param  durationInMinutes  int value for durationInMinutes.
         * @param  genre  String value for genre.
         * @param  director  String value for director.
         * @param  releaseDate  String value for releaseDate.
         */
        public Builder(String title, int numberOfSeasons, int numberOfEpisodes,
                int durationInMinutes, String genre, String director, String releaseDate) {
            this.title = title;
            this.numberOfSeasons = numberOfSeasons;
            this.numberOfEpisodes = numberOfEpisodes;
            this.durationInMinutes = durationInMinutes;
            this.genre = genre;
            this.director = director;
            this.releaseDate = releaseDate;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for numberOfSeasons.
         * @param  numberOfSeasons  int value for numberOfSeasons.
         * @return Builder
         */
        public Builder numberOfSeasons(int numberOfSeasons) {
            this.numberOfSeasons = numberOfSeasons;
            return this;
        }

        /**
         * Setter for numberOfEpisodes.
         * @param  numberOfEpisodes  int value for numberOfEpisodes.
         * @return Builder
         */
        public Builder numberOfEpisodes(int numberOfEpisodes) {
            this.numberOfEpisodes = numberOfEpisodes;
            return this;
        }

        /**
         * Setter for durationInMinutes.
         * @param  durationInMinutes  int value for durationInMinutes.
         * @return Builder
         */
        public Builder durationInMinutes(int durationInMinutes) {
            this.durationInMinutes = durationInMinutes;
            return this;
        }

        /**
         * Setter for genre.
         * @param  genre  String value for genre.
         * @return Builder
         */
        public Builder genre(String genre) {
            this.genre = genre;
            return this;
        }

        /**
         * Setter for director.
         * @param  director  String value for director.
         * @return Builder
         */
        public Builder director(String director) {
            this.director = director;
            return this;
        }

        /**
         * Setter for releaseDate.
         * @param  releaseDate  String value for releaseDate.
         * @return Builder
         */
        public Builder releaseDate(String releaseDate) {
            this.releaseDate = releaseDate;
            return this;
        }

        /**
         * Builds a new {@link AddSeriesRequest} object using the set fields.
         * @return {@link AddSeriesRequest}
         */
        public AddSeriesRequest build() {
            return new AddSeriesRequest(title, numberOfSeasons, numberOfEpisodes, durationInMinutes,
                    genre, director, releaseDate);
        }
    }
}
