/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Content type.
 */
public class Content {
    private int contentId;
    private String contentType;

    /**
     * Default constructor.
     */
    public Content() {
    }

    /**
     * Initialization constructor.
     * @param  contentId  int value for contentId.
     * @param  contentType  String value for contentType.
     */
    public Content(
            int contentId,
            String contentType) {
        this.contentId = contentId;
        this.contentType = contentType;
    }

    /**
     * Getter for ContentId.
     * @return Returns the int
     */
    @JsonGetter("contentId")
    public int getContentId() {
        return contentId;
    }

    /**
     * Setter for ContentId.
     * @param contentId Value for int
     */
    @JsonSetter("contentId")
    public void setContentId(int contentId) {
        this.contentId = contentId;
    }

    /**
     * Getter for ContentType.
     * @return Returns the String
     */
    @JsonGetter("contentType")
    public String getContentType() {
        return contentType;
    }

    /**
     * Setter for ContentType.
     * @param contentType Value for String
     */
    @JsonSetter("contentType")
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Converts this Content into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Content [" + "contentId=" + contentId + ", contentType=" + contentType + "]";
    }

    /**
     * Builds a new {@link Content.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Content.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(contentId, contentType);
        return builder;
    }

    /**
     * Class to build instances of {@link Content}.
     */
    public static class Builder {
        private int contentId;
        private String contentType;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  contentId  int value for contentId.
         * @param  contentType  String value for contentType.
         */
        public Builder(int contentId, String contentType) {
            this.contentId = contentId;
            this.contentType = contentType;
        }

        /**
         * Setter for contentId.
         * @param  contentId  int value for contentId.
         * @return Builder
         */
        public Builder contentId(int contentId) {
            this.contentId = contentId;
            return this;
        }

        /**
         * Setter for contentType.
         * @param  contentType  String value for contentType.
         * @return Builder
         */
        public Builder contentType(String contentType) {
            this.contentType = contentType;
            return this;
        }

        /**
         * Builds a new {@link Content} object using the set fields.
         * @return {@link Content}
         */
        public Content build() {
            return new Content(contentId, contentType);
        }
    }
}
