/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for LoginUserRequest type.
 */
public class LoginUserRequest {
    private String userName;
    private String password;

    /**
     * Default constructor.
     */
    public LoginUserRequest() {
    }

    /**
     * Initialization constructor.
     * @param  userName  String value for userName.
     * @param  password  String value for password.
     */
    public LoginUserRequest(
            String userName,
            String password) {
        this.userName = userName;
        this.password = password;
    }

    /**
     * Getter for UserName.
     * @return Returns the String
     */
    @JsonGetter("userName")
    public String getUserName() {
        return userName;
    }

    /**
     * Setter for UserName.
     * @param userName Value for String
     */
    @JsonSetter("userName")
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Getter for Password.
     * @return Returns the String
     */
    @JsonGetter("password")
    public String getPassword() {
        return password;
    }

    /**
     * Setter for Password.
     * @param password Value for String
     */
    @JsonSetter("password")
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Converts this LoginUserRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LoginUserRequest [" + "userName=" + userName + ", password=" + password + "]";
    }

    /**
     * Builds a new {@link LoginUserRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LoginUserRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(userName, password);
        return builder;
    }

    /**
     * Class to build instances of {@link LoginUserRequest}.
     */
    public static class Builder {
        private String userName;
        private String password;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  userName  String value for userName.
         * @param  password  String value for password.
         */
        public Builder(String userName, String password) {
            this.userName = userName;
            this.password = password;
        }

        /**
         * Setter for userName.
         * @param  userName  String value for userName.
         * @return Builder
         */
        public Builder userName(String userName) {
            this.userName = userName;
            return this;
        }

        /**
         * Setter for password.
         * @param  password  String value for password.
         * @return Builder
         */
        public Builder password(String password) {
            this.password = password;
            return this;
        }

        /**
         * Builds a new {@link LoginUserRequest} object using the set fields.
         * @return {@link LoginUserRequest}
         */
        public LoginUserRequest build() {
            return new LoginUserRequest(userName, password);
        }
    }
}
