/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for RegisterUserRequest type.
 */
public class RegisterUserRequest {
    private String userName;
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private String password;

    /**
     * Default constructor.
     */
    public RegisterUserRequest() {
    }

    /**
     * Initialization constructor.
     * @param  userName  String value for userName.
     * @param  firstName  String value for firstName.
     * @param  lastName  String value for lastName.
     * @param  email  String value for email.
     * @param  phone  String value for phone.
     * @param  password  String value for password.
     */
    public RegisterUserRequest(
            String userName,
            String firstName,
            String lastName,
            String email,
            String phone,
            String password) {
        this.userName = userName;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.password = password;
    }

    /**
     * Getter for UserName.
     * @return Returns the String
     */
    @JsonGetter("userName")
    public String getUserName() {
        return userName;
    }

    /**
     * Setter for UserName.
     * @param userName Value for String
     */
    @JsonSetter("userName")
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Getter for FirstName.
     * @return Returns the String
     */
    @JsonGetter("firstName")
    public String getFirstName() {
        return firstName;
    }

    /**
     * Setter for FirstName.
     * @param firstName Value for String
     */
    @JsonSetter("firstName")
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for LastName.
     * @return Returns the String
     */
    @JsonGetter("lastName")
    public String getLastName() {
        return lastName;
    }

    /**
     * Setter for LastName.
     * @param lastName Value for String
     */
    @JsonSetter("lastName")
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    @JsonGetter("email")
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for Phone.
     * @return Returns the String
     */
    @JsonGetter("phone")
    public String getPhone() {
        return phone;
    }

    /**
     * Setter for Phone.
     * @param phone Value for String
     */
    @JsonSetter("phone")
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for Password.
     * @return Returns the String
     */
    @JsonGetter("password")
    public String getPassword() {
        return password;
    }

    /**
     * Setter for Password.
     * @param password Value for String
     */
    @JsonSetter("password")
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Converts this RegisterUserRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RegisterUserRequest [" + "userName=" + userName + ", firstName=" + firstName
                + ", lastName=" + lastName + ", email=" + email + ", phone=" + phone + ", password="
                + password + "]";
    }

    /**
     * Builds a new {@link RegisterUserRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RegisterUserRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(userName, firstName, lastName, email, phone, password);
        return builder;
    }

    /**
     * Class to build instances of {@link RegisterUserRequest}.
     */
    public static class Builder {
        private String userName;
        private String firstName;
        private String lastName;
        private String email;
        private String phone;
        private String password;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  userName  String value for userName.
         * @param  firstName  String value for firstName.
         * @param  lastName  String value for lastName.
         * @param  email  String value for email.
         * @param  phone  String value for phone.
         * @param  password  String value for password.
         */
        public Builder(String userName, String firstName, String lastName, String email,
                String phone, String password) {
            this.userName = userName;
            this.firstName = firstName;
            this.lastName = lastName;
            this.email = email;
            this.phone = phone;
            this.password = password;
        }

        /**
         * Setter for userName.
         * @param  userName  String value for userName.
         * @return Builder
         */
        public Builder userName(String userName) {
            this.userName = userName;
            return this;
        }

        /**
         * Setter for firstName.
         * @param  firstName  String value for firstName.
         * @return Builder
         */
        public Builder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Setter for lastName.
         * @param  lastName  String value for lastName.
         * @return Builder
         */
        public Builder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for phone.
         * @param  phone  String value for phone.
         * @return Builder
         */
        public Builder phone(String phone) {
            this.phone = phone;
            return this;
        }

        /**
         * Setter for password.
         * @param  password  String value for password.
         * @return Builder
         */
        public Builder password(String password) {
            this.password = password;
            return this;
        }

        /**
         * Builds a new {@link RegisterUserRequest} object using the set fields.
         * @return {@link RegisterUserRequest}
         */
        public RegisterUserRequest build() {
            return new RegisterUserRequest(userName, firstName, lastName, email, phone, password);
        }
    }
}
