/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for UpdateFavoriteRequest type.
 */
public class UpdateFavoriteRequest {
    private int id;
    private Content content;
    private int userId;

    /**
     * Default constructor.
     */
    public UpdateFavoriteRequest() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  content  Content value for content.
     * @param  userId  int value for userId.
     */
    public UpdateFavoriteRequest(
            int id,
            Content content,
            int userId) {
        this.id = id;
        this.content = content;
        this.userId = userId;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Content.
     * @return Returns the Content
     */
    @JsonGetter("content")
    public Content getContent() {
        return content;
    }

    /**
     * Setter for Content.
     * @param content Value for Content
     */
    @JsonSetter("content")
    public void setContent(Content content) {
        this.content = content;
    }

    /**
     * Getter for UserId.
     * @return Returns the int
     */
    @JsonGetter("user_id")
    public int getUserId() {
        return userId;
    }

    /**
     * Setter for UserId.
     * @param userId Value for int
     */
    @JsonSetter("user_id")
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * Converts this UpdateFavoriteRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateFavoriteRequest [" + "id=" + id + ", content=" + content + ", userId="
                + userId + "]";
    }

    /**
     * Builds a new {@link UpdateFavoriteRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateFavoriteRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, content, userId);
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateFavoriteRequest}.
     */
    public static class Builder {
        private int id;
        private Content content;
        private int userId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  content  Content value for content.
         * @param  userId  int value for userId.
         */
        public Builder(int id, Content content, int userId) {
            this.id = id;
            this.content = content;
            this.userId = userId;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for content.
         * @param  content  Content value for content.
         * @return Builder
         */
        public Builder content(Content content) {
            this.content = content;
            return this;
        }

        /**
         * Setter for userId.
         * @param  userId  int value for userId.
         * @return Builder
         */
        public Builder userId(int userId) {
            this.userId = userId;
            return this;
        }

        /**
         * Builds a new {@link UpdateFavoriteRequest} object using the set fields.
         * @return {@link UpdateFavoriteRequest}
         */
        public UpdateFavoriteRequest build() {
            return new UpdateFavoriteRequest(id, content, userId);
        }
    }
}
