/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for UpdateRatingRequest type.
 */
public class UpdateRatingRequest {
    private int id;
    private int userId;
    private Content2 content;
    private int value;

    /**
     * Default constructor.
     */
    public UpdateRatingRequest() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  userId  int value for userId.
     * @param  content  Content2 value for content.
     * @param  value  int value for value.
     */
    public UpdateRatingRequest(
            int id,
            int userId,
            Content2 content,
            int value) {
        this.id = id;
        this.userId = userId;
        this.content = content;
        this.value = value;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for UserId.
     * @return Returns the int
     */
    @JsonGetter("userId")
    public int getUserId() {
        return userId;
    }

    /**
     * Setter for UserId.
     * @param userId Value for int
     */
    @JsonSetter("userId")
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * Getter for Content.
     * @return Returns the Content2
     */
    @JsonGetter("content")
    public Content2 getContent() {
        return content;
    }

    /**
     * Setter for Content.
     * @param content Value for Content2
     */
    @JsonSetter("content")
    public void setContent(Content2 content) {
        this.content = content;
    }

    /**
     * Getter for Value.
     * @return Returns the int
     */
    @JsonGetter("value")
    public int getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * @param value Value for int
     */
    @JsonSetter("value")
    public void setValue(int value) {
        this.value = value;
    }

    /**
     * Converts this UpdateRatingRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateRatingRequest [" + "id=" + id + ", userId=" + userId + ", content=" + content
                + ", value=" + value + "]";
    }

    /**
     * Builds a new {@link UpdateRatingRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateRatingRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, userId, content, value);
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateRatingRequest}.
     */
    public static class Builder {
        private int id;
        private int userId;
        private Content2 content;
        private int value;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  userId  int value for userId.
         * @param  content  Content2 value for content.
         * @param  value  int value for value.
         */
        public Builder(int id, int userId, Content2 content, int value) {
            this.id = id;
            this.userId = userId;
            this.content = content;
            this.value = value;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for userId.
         * @param  userId  int value for userId.
         * @return Builder
         */
        public Builder userId(int userId) {
            this.userId = userId;
            return this;
        }

        /**
         * Setter for content.
         * @param  content  Content2 value for content.
         * @return Builder
         */
        public Builder content(Content2 content) {
            this.content = content;
            return this;
        }

        /**
         * Setter for value.
         * @param  value  int value for value.
         * @return Builder
         */
        public Builder value(int value) {
            this.value = value;
            return this;
        }

        /**
         * Builds a new {@link UpdateRatingRequest} object using the set fields.
         * @return {@link UpdateRatingRequest}
         */
        public UpdateRatingRequest build() {
            return new UpdateRatingRequest(id, userId, content, value);
        }
    }
}
