/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for UpdateCommentRequest type.
 */
public class UpdateCommentRequest {
    private int id;
    private String comment;
    private int userId;
    private Content content;

    /**
     * Default constructor.
     */
    public UpdateCommentRequest() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  comment  String value for comment.
     * @param  userId  int value for userId.
     * @param  content  Content value for content.
     */
    public UpdateCommentRequest(
            int id,
            String comment,
            int userId,
            Content content) {
        this.id = id;
        this.comment = comment;
        this.userId = userId;
        this.content = content;
    }

    /**
     * Getter for Id.
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Comment.
     * @return Returns the String
     */
    @JsonGetter("comment")
    public String getComment() {
        return comment;
    }

    /**
     * Setter for Comment.
     * @param comment Value for String
     */
    @JsonSetter("comment")
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for UserId.
     * @return Returns the int
     */
    @JsonGetter("userId")
    public int getUserId() {
        return userId;
    }

    /**
     * Setter for UserId.
     * @param userId Value for int
     */
    @JsonSetter("userId")
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * Getter for Content.
     * @return Returns the Content
     */
    @JsonGetter("content")
    public Content getContent() {
        return content;
    }

    /**
     * Setter for Content.
     * @param content Value for Content
     */
    @JsonSetter("content")
    public void setContent(Content content) {
        this.content = content;
    }

    /**
     * Converts this UpdateCommentRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateCommentRequest [" + "id=" + id + ", comment=" + comment + ", userId=" + userId
                + ", content=" + content + "]";
    }

    /**
     * Builds a new {@link UpdateCommentRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateCommentRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, comment, userId, content);
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateCommentRequest}.
     */
    public static class Builder {
        private int id;
        private String comment;
        private int userId;
        private Content content;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  comment  String value for comment.
         * @param  userId  int value for userId.
         * @param  content  Content value for content.
         */
        public Builder(int id, String comment, int userId, Content content) {
            this.id = id;
            this.comment = comment;
            this.userId = userId;
            this.content = content;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for comment.
         * @param  comment  String value for comment.
         * @return Builder
         */
        public Builder comment(String comment) {
            this.comment = comment;
            return this;
        }

        /**
         * Setter for userId.
         * @param  userId  int value for userId.
         * @return Builder
         */
        public Builder userId(int userId) {
            this.userId = userId;
            return this;
        }

        /**
         * Setter for content.
         * @param  content  Content value for content.
         * @return Builder
         */
        public Builder content(Content content) {
            this.content = content;
            return this;
        }

        /**
         * Builds a new {@link UpdateCommentRequest} object using the set fields.
         * @return {@link UpdateCommentRequest}
         */
        public UpdateCommentRequest build() {
            return new UpdateCommentRequest(id, comment, userId, content);
        }
    }
}
