/*
 * EAFinalProjectLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package localhost8089.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import localhost8089.ApiHelper;
import localhost8089.EAFinalProjectClient;
import localhost8089.exceptions.ApiException;
import localhost8089.models.AddCommentRequest;
import localhost8089.models.UpdateCommentRequest;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class CommentServiceControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static EAFinalProjectClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static CommentServiceController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getCommentServiceController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Test case for Get Comments.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testGetComments() throws Exception {

        // Set callback and perform API call
        try {
            controller.getComments();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Test case for Get Comment.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testGetComment() throws Exception {

        // Set callback and perform API call
        try {
            controller.getComment();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Test case for Update Comment.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testUpdateComment() throws Exception {
        // Parameters for the API call
        UpdateCommentRequest body = ApiHelper.deserialize(
                "{\r\n  \"id\": 1,\r\n  \"comment\": \"movie 2 is bad\",\r\n  \"userId\": 1,\r\n  "
                + "\"content\": {\r\n    \"contentId\": 1,\r\n    \"contentType\": \"series\"\r\n  "
                + "}\r\n}",
                UpdateCommentRequest.class);

        // Set callback and perform API call
        try {
            controller.updateComment(body);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Test case for Delete Comment.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testDeleteComment() throws Exception {

        // Set callback and perform API call
        try {
            controller.deleteComment();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Test case for Add Comment.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testAddComment() throws Exception {
        // Parameters for the API call
        AddCommentRequest body = ApiHelper.deserialize(
                "{\r\n  \"comment\": \"movie 2 is bad\",\r\n  \"userId\": 1,\r\n  \"content\": {\r"
                + "\n    \"contentId\": 1,\r\n    \"contentType\": \"series\"\r\n  }\r\n}",
                AddCommentRequest.class);

        // Set callback and perform API call
        try {
            controller.addComment(body);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
